### ISSUE TITLE
Unable to close due to unfinalized statements or unfinished backups

### ISSUE THREAD

**Issue by Yoplitein** [biozic/d2sqlite3#10]
I was tweaking the example code, came up with this:

```d
auto db = Database(":memory:");

db.execute(
    "CREATE TABLE person (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        score FLOAT
     )"
);

auto statement = db.prepare(
    "INSERT INTO person (name, score)
     VALUES (?, ?)"
);

statement.bindAll("John", null);
statement.execute;

statement = db.prepare("SELECT name FROM person");
auto data = statement.execute;

foreach(row; data)
    writeln(row.peek!string(0));
```

and it throws `error 5: unable to close due to unfinalized statements or unfinished backups` after exiting main. Also happens if close is explicitly called.
I did some poking around and it seems to be caused by the Statement's payload not being destructed properly? I'm not sure.

Tested on Linux with dmd 2.066.

**Comment by denizzzka** [comment]
try to reset query result after foreach statement:
data.reset();

**Comment by biozic** [comment]
@Yoplitein To me, your code is valid, but it only seems to work if you add parentheses after execute as in:
```d
statement.execute();
```
If you can confirm, I will investigate...

**Comment by biozic** [comment]
https://issues.dlang.org/show_bug.cgi?id=14264

**Comment by Yoplitein** [comment]
That does seem to be the issue. I also tested with LDC and it seems to behave exactly as dmd. Really weird.
