### ISSUE TITLE
Binding string to a sql statement doesn't work

### ISSUE THREAD

**Issue by ghost** [biozic/d2sqlite3#11]
something like..
string company = "DMD";
auto statement = stocks.prepare(
        "INSERT INTO COMPANIES (name) VALUES (:name)");  
                statement.bind(":name", company);
[..execute & reset.]

results in
../../../../.dub/packages/d2sqlite3-0.7.1/source/d2sqlite3.d(1082): Error: undefined identifier sqlite3_bind_text64, did you mean function sqlite3_bind_text?

I'm using Linux Mint 17 / x64.

Regards, Ozan

**Comment by biozic** [comment]
`sqlite3_bind_text64` is defined in the sqlite3 module that comes along with the d2sqlite3 module and is publicly imported by it. Check that you are not importing etc.c.sqlite3 instead, or that you have a clean install of v0.7.1.
