### ISSUE TITLE
Trouble Installing on OSX

### ISSUE THREAD

**Issue by volomike** [biozic/d2sqlite3#18]
Not really knowing what I'm doing just (new to C++, new to D), I wrote this:

```
// I am named test.d
import d2sqlite3;
import std.array;
import std.conv;
import std.exception;
import std.file;
import std.path;
import std.stdio;
import std.string;
import std.c.stdlib : exit;
import core.stdc.time : time_t;
import etc.c.zlib;

void main(){

	auto db = Database("test.sqlite");
	auto results = db.execute("SELECT * FROM test");
	while (!results.empty) {
		auto row = results.front;
		writeln(row.peek!string(0));
		results.popFront();
	}

}
```

on OSX (Yosemite) and when I compile, I get:

$ dmd test.d
Undefined symbols for architecture x86_64:
  "_D9d2sqlite311ResultRange11__fieldDtorMFZv", referenced from:
      __Dmain in test.o
  "_D9d2sqlite311ResultRange5emptyMFNdZb", referenced from:
      __Dmain in test.o
  "_D9d2sqlite311ResultRange5frontMFNdZS9d2sqlite33Row", referenced from:
      __Dmain in test.o
  "_D9d2sqlite311ResultRange8_Payload11__fieldDtorMFZv", referenced from:
      _D42TypeInfo_S9d2sqlite311ResultRange8_Payload6__initZ in test.o
  "_D9d2sqlite311ResultRange8_Payload11__xopEqualsFKxS9d2sqlite311ResultRange8_PayloadKxS9d2sqlite311ResultRange8_PayloadZb", referenced from:
      _D42TypeInfo_S9d2sqlite311ResultRange8_Payload6__initZ in test.o
  "_D9d2sqlite311ResultRange8popFrontMFZv", referenced from:
      __Dmain in test.o
  "_D9d2sqlite312__ModuleInfoZ", referenced from:
      _D4test12__ModuleInfoZ in test.o
  "_D9d2sqlite33Row13internalIndexMFiZi", referenced from:
      _D9d2sqlite33Row13__T4peekTAyaZ4peekMFiZAya in test.o
  "_D9d2sqlite38Database11__fieldDtorMFZv", referenced from:
      __Dmain in test.o
  "_D9d2sqlite38Database6__ctorMFNcAyaiZS9d2sqlite38Database", referenced from:
      __Dmain in test.o
  "_D9d2sqlite38Database7executeMFAyaZS9d2sqlite311ResultRange", referenced from:
      __Dmain in test.o
  "_D9d2sqlite38Database8_Payload6__dtorMFZv", referenced from:
      _D38TypeInfo_S9d2sqlite38Database8_Payload6__initZ in test.o
  "_D9d2sqlite39Statement8_Payload10__aggrDtorMFZv", referenced from:
      _D39TypeInfo_S9d2sqlite39Statement8_Payload6__initZ in test.o
  "_D9d2sqlite39Statement8_Payload11__xopEqualsFKxS9d2sqlite39Statement8_PayloadKxS9d2sqlite39Statement8_PayloadZb", referenced from:
      _D39TypeInfo_S9d2sqlite39Statement8_Payload6__initZ in test.o
  "_sqlite3_column_text", referenced from:
      _D9d2sqlite33Row13__T4peekTAyaZ4peekMFiZAya in test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1

**Comment by aldacron** [comment]
You didn't link anything. You will need to link with both d2sqlite3 and sqlite3. The simplest thing to do is to use DUB to manage your project.

**Comment by volomike** [comment]
Within seconds of you answering me here, remarkably on the DLang forums a
guy named Jacob explained to me the whole DUB process as well as how to
link things. I managed to get a working executable now that spits out the
contents of my sqlite3 database table. Exciting and fun!
