### ISSUE TITLE
Usages of `ulong` should be statically rejected?

### ISSUE THREAD

**Issue by sinkuu** [biozic/d2sqlite3#21]
d2sqlite3 functions accept any integral types, but SQLite's `INTEGER` is signed integer up to 64 bits. So it can't correctly deal with `ulong`, unsigned 64 bits integer.

**Comment by biozic** [comment]
There can be an incorrect behavior with `Statement.bind`. In fact, there stil are ugly casts in the `Statement.bind` functions that should be replaced with `std.to` calls, that would throw overflow exceptions. It's easy to fix. But statically rejecting `ulong` might be too vehement.

**Comment by biozic** [comment]
See a1c18bc4818de43a6c13c83f6440896e75f8d0fa

**Comment by sinkuu** [comment]
Thank you!
