### ISSUE TITLE
Read blob without copying

### ISSUE THREAD

**Issue by MrSmith33** [biozic/d2sqlite3#23]
There should be a way to get access to read blob without memory allocation.
`peek()` can be split into `peek()` and `peekDup()` or `peek()` and `peekNoDup()`.

In my case I want to read data uncompress it and then copy to output buffer passed to me.

Edit: better ensure that peek for blobs happens only when T is ubyte[] or string

**Comment by biozic** [comment]
I agree. Maybe we could even use the [BLOB I/O API](https://www.sqlite.org/c3ref/blob_open.html) to read/write portions of or an entire BLOB into/from a buffer. Actually, it was a work in process, but I never finished it.

In the mean time, we could indeed have a `void peekInto(int index, out ubyte[] buffer)` method (or whatever name we choose).

But choosing the right version of peek would be up to the user, still.

**Comment by MrSmith33** [comment]
`void peekInto(int index, out ubyte[] buffer)` assumes that data would be *copied* into `buffer`, while I mean retreiving slice to data that sqlite returned, without copying. Something like that:
``` D
T peekNoDup(T)(int index)
	if (isArray!T && !isSomeString!T)
{
	auto i = internalIndex(index);
	auto ptr = sqlite3_column_blob(statement, i);
	auto length = sqlite3_column_bytes(statement, i);
	return cast(T)ptr[0..length];
}
```

But having version with out buffer is also useful!

**Comment by biozic** [comment]
OK sorry I misread what you needed. Is 7a6a1d8e47660e1cff27a154d615ee4a0d3159c2 OK?
I added a warning in the documentation, that the returned data will be invalid sooner than later.

**Comment by MrSmith33** [comment]
Yes, thanks for implementation!
