### ISSUE TITLE
DB is not closed properly

### ISSUE THREAD

**Issue by tchaloupka** [biozic/d2sqlite3#29]
I noticed a problem with connections remaining open even after connection close is called.

This is minimal test which does not work for me:

``` D
void main()
{
    void test()
    {
        auto db = Database(":memory:");
        db.run("CREATE TABLE items (name TEXT);
            INSERT INTO items VALUES ('dog');
            INSERT INTO items VALUES ('cat');");

        auto res = db.execute("SELECT name FROM items");
        foreach(ref row; res) {}

        db.close();
    }

    test();
    readln();
}
```

After test function call, sqlite3_close is not called from Payload destructor.

When the foreach is removed it works ok.

Tried with v0.9.7 and dmd-2.070.2 and 2.071-beta2, ldc-0.17.1

**Comment by biozic** [comment]
Right. So there's probably a bug in the reference count that shows when using `ref` in `foreach`. Can you confirm it works when `ref` is not used?

**Comment by chalucha** [comment]
No, I tried that already with foreach(row; res) {} with the same result.
