### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'

### ISSUE THREAD

**Issue by alex1a** [biozic/d2sqlite3#49]
Anyone experience this error with Windows ?

* System: Windows x64
* Shell: CMD / Admin CMD

```
LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64\link.exe failed with status: 1181
ldc2 failed with exit code 1.
```

**Comment by alex1a** [comment]
Sorry for opening a issue, just need to put **sqlite3.lib** file where my **dub.json** file is 😢

**Comment by alex1a** [comment]
i need to copy sqlite3.lib to "lib/win64" in project's root directory and add this lines to dub.json

`{
	...

	"lflags-windows-x86_64-ldc": ["-Llib\\win64"],
	"libs": ["sqlite3"]
}`

**Comment by liudonghua123** [comment]
I tried the instructions on https://gist.github.com/zeljic/d8b542788b225b1bcb5fce169ee28c55, and finally I can build sqlite3.lib.

### How to build SQLite3 .lib file on Windows 10

1. Download source from [source](https://www.sqlite.org/download.html) (https://www.sqlite.org/download.html)

	For example: [source](https://www.sqlite.org/2020/sqlite-amalgamation-3310100.zip) `https://www.sqlite.org/2020/sqlite-amalgamation-3310100.zip`
2. Download binary from [binary](https://www.sqlite.org/download.html)

	For example: [binary](https://www.sqlite.org/2020/sqlite-dll-win64-x64-3310100.zip) `https://www.sqlite.org/2020/sqlite-dll-win64-x64-3310100.zip`
    
3. Extract both archives to the same directory
    
4. Open **Developer Command Prompt for VS 2017** by typing *Developer Command* in Windows Search

5. Go to directory where you've extracted **source code** and **binary** files (via opened cmd)
6. Run 
	```lib /DEF:sqlite3.def /OUT:sqlite3.lib /MACHINE:x64```

**Comment by HezinTUKE** [comment]
This helped me :

https://github.com/rusqlite/rusqlite#user-content-notes-on-building-rusqlite-and-libsqlite3-sys
