### ISSUE TITLE
Calling close() on a Database manually causes API errors

### ISSUE THREAD

**Issue by AndrejMitrovic** [biozic/d2sqlite3#54]
```D
import std.conv;
import std.stdio;

import d2sqlite3.database;
import d2sqlite3.library;
import d2sqlite3.sqlite3;

static extern(C) void loggerCallback (void *arg, int code,
    const(char)* msg) nothrow
{
    try
    {
        writefln("SQLite error: (%s) %s", code, msg.to!string);
    }
    catch (Exception ex)
    {
    }
}

unittest
{
    shutdown();
    config(SQLITE_CONFIG_MULTITHREAD);
    config(SQLITE_CONFIG_LOG, &loggerCallback, null);
    initialize();

    auto db = Database(":memory:");
    db.close();
}
```

Result:

```
SQLite error: (21) API call with invalid database connection pointer
SQLite error: (21) misuse at line 152877 of [89e099fbe5]
```

----

One other thing I don't understand. Why is the `shutdown` call necessary before `SQLITE_CONFIG_LOG` is configured? If I don't call `shutdown` first, I get this error:

```
d2sqlite3.database.SqliteException@source/d2sqlite3/library.d(88): Configuration: error 21
```

And according to the `d2sqlite3` unittests, it also calls shutdown before any initialization. Is this a workaround for something?

**Comment by AndrejMitrovic** [comment]
Forgot to mention I'm testing this on OSX.

**Comment by AndrejMitrovic** [comment]
Without the explicit `db.close` call, I will eventually get this:

```
Error: clean-up of Database incorrectly depends on destructors called by the GC.
```

**Comment by biozic** [comment]
Thanks for reporting!

There's a (stupid) bug that causes the database connection to be closed twice when calling `Database.close()` explicitly, leading to the 21 'misuse' error. Should be fixed soon.

The SQLite [documentation](https://www.sqlite.org/c3ref/config.html) says all configuration must be done before `sqlite3_initialize` and after `sqlite3_shutdown` has been called. That's why the unit test was written this way.

**Comment by biozic** [comment]
> ```
> Error: clean-up of Database incorrectly depends on destructors called by the GC.
> ```
I think this is an independent bug in your code: a Database connection cannot be closed by a destructor called by the GC.

**Comment by AndrejMitrovic** [comment]
> Should be fixed soon.

Ah, thank you so much! Very fast fix. :)

> I think this is an independent bug in your code: a Database connection cannot be closed by a destructor called by the GC.

Indeed, it was.
