### ISSUE TITLE
Not compiling for 2.066.1 and 2.065

### ISSUE THREAD

**Issue by rikkimax** [biozic/d2sqlite3#6]
http://forum.dlang.org/post/yyhxcmskmbantvqodopa@forum.dlang.org

**Comment by biozic** [comment]
Compiles for me with 2.066.1. I haven't tested 2.065 yet.

**Comment by denizzzka** [comment]
Compiles for me with 2.066.1 too

**Comment by biozic** [comment]
Compiles with 2.065, 2.066.1 and 2.067-b3.
